# Generated by Django 3.1.3 on 2020-12-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDChar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='id',
        ),
        migrations.AlterField(
            model_name='background',
            name='bg_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
